const ROOT = "/runtime-assets/unified-v001";

export const UNIFIED_RUNTIME_ASSETS = {
  hud: {
    levelBase: `${ROOT}/resources/lv_exp/global_hud/lvexp_hud_base.png`,
    levelFill: `${ROOT}/resources/lv_exp/global_hud/lvexp_hud_progress_fill.png`,
    levelTrack: `${ROOT}/resources/lv_exp/global_hud/lvexp_hud_progress_track.png`,
    starsFrame: `${ROOT}/resources/stars/hud/stars_hud_frame.png`,
    starsIcon: `${ROOT}/resources/stars/hud/stars_hud_icon.png`,
    starsReceiving: `${ROOT}/knowledge/hud/hud_stars_receiving.png`,
    starsReducedMotion: `${ROOT}/knowledge/hud/hud_stars_reduced_motion.png`,
    energyIdle: `${ROOT}/resources/energy/global_hud/energy_hud_idle.png`,
    energyFull: `${ROOT}/resources/energy/global_hud/energy_hud_full.png`,
    energyFill: `${ROOT}/resources/energy/fill/energy_hud_fill.png`,
    energySymbol: `${ROOT}/resources/energy/symbol/energy_hud_symbol.png`,
    settingsIdle: `${ROOT}/knowledge/hud/hud_settings_idle.png`,
    settingsFocus: `${ROOT}/knowledge/hud/hud_settings_focus.png`,
    settingsPressed: `${ROOT}/knowledge/hud/hud_settings_pressed.png`,
    settingsReducedMotion: `${ROOT}/knowledge/hud/hud_settings_reduced_motion.png`,
  },
  dialogue: {
    rabbitLeft: `${ROOT}/dialogue/rabbit/rabbit_bubble_left.png`,
    rabbitRight: `${ROOT}/dialogue/rabbit/rabbit_bubble_right.png`,
    marmotLeft: `${ROOT}/dialogue/marmot/marmot_bubble_left.png`,
    marmotRight: `${ROOT}/dialogue/marmot/marmot_bubble_right.png`,
    reduced: `${ROOT}/dialogue/reduced_motion/bubble_reduced_motion_static.png`,
    close: `${ROOT}/dialogue/shared_master/close_affordance.png`,
    continue: `${ROOT}/dialogue/shared_master/continue_affordance.png`,
  },
  mission: {
    boardBase: `${ROOT}/mission/shared_master/board_base.png`,
    boardFrame: `${ROOT}/mission/shared_master/board_frame.png`,
    boardShadow: `${ROOT}/mission/shared_master/board_shadow.png`,
    todaySection: `${ROOT}/mission/shared_master/today_section_base.png`,
    weeklySection: `${ROOT}/mission/shared_master/weekly_section_base.png`,
    dailyTab: `${ROOT}/mission/formal_authority/mission/board/game_mission_tab_daily.png`,
    weeklyTab: `${ROOT}/mission/formal_authority/mission/board/game_mission_tab_weekly.png`,
    paper: `${ROOT}/mission/formal_authority/mission/papers/game_mission_paper_base.png`,
    paperShadow: `${ROOT}/mission/shared_master/mission_paper_shadow.png`,
    available: `${ROOT}/mission/formal_authority/mission/states/game_mission_item_idle.png`,
    completed: `${ROOT}/mission/formal_authority/mission/states/game_mission_item_complete.png`,
    claimable: `${ROOT}/mission/formal_authority/mission/states/game_mission_item_claimable.png`,
    pending: `${ROOT}/mission/formal_authority/reward/source/scene_native_states/mission_paper_loading_state.png`,
    claimed: `${ROOT}/mission/formal_authority/mission/states/game_mission_item_claimed.png`,
    claimButton: `${ROOT}/mission/formal_authority/mission/indicators/game_mission_claim_button.png`,
    claimIndicator: `${ROOT}/mission/formal_authority/mission/indicators/game_mission_claim_indicator.png`,
    claimedStamp: `${ROOT}/mission/shared_master/claimed_stamp.png`,
    empty: `${ROOT}/mission/formal_authority/mission/states/game_mission_empty.png`,
    close: `${ROOT}/mission/formal_authority/mission/indicators/game_mission_close.png`,
  },
  knowledge: {
    background: `${ROOT}/knowledge/base/knowledge_board_background_scene.png`,
    shadow: `${ROOT}/knowledge/base/knowledge_board_shadow.png`,
    board: `${ROOT}/knowledge/board/knowledge_board_wood_structure.png`,
    title: `${ROOT}/knowledge/board/knowledge_board_title_plaque.png`,
    vines: `${ROOT}/knowledge/board/knowledge_board_vines_fixed.png`,
    paper: `${ROOT}/knowledge/question/knowledge_board_question_paper.png`,
    optionIdle: [1, 2, 3].map((slot) => `${ROOT}/knowledge/options/knowledge_option_slot_0${slot}_idle.png`),
    optionSelected: [1, 2, 3].map((slot) => `${ROOT}/knowledge/options/knowledge_option_slot_0${slot}_selected.png`),
    optionCorrect: [1, 2, 3].map((slot) => `${ROOT}/knowledge/options/knowledge_option_slot_0${slot}_correct.png`),
    optionWrong: [1, 2, 3].map((slot) => `${ROOT}/knowledge/options/knowledge_option_slot_0${slot}_wrong.png`),
    submit: `${ROOT}/knowledge/submit/knowledge_submit_idle.png`,
    submitDisabled: `${ROOT}/knowledge/submit/knowledge_submit_disabled.png`,
    correctStamp: `${ROOT}/knowledge/states/correct/knowledge_correct_stamp.png`,
    locked: `${ROOT}/knowledge/states/errors/knowledge_level_locked_state.png`,
    completed: `${ROOT}/knowledge/states/completed/knowledge_completed_reopen_state.png`,
    close: `${ROOT}/knowledge/close/knowledge_close_idle.png`,
  },
  starsSummary: {
    base: `${ROOT}/resources/stars/summary/stars_summary_base.png`,
    ready: `${ROOT}/resources/stars/summary/stars_summary_ready.png`,
    close: `${ROOT}/resources/stars/summary/stars_summary_close_world_control.png`,
  },
  settings: {
    overlayBase: `${ROOT}/settings/shared_master/overlay_base.png`,
    overlayBorder: `${ROOT}/settings/shared_master/overlay_border.png`,
    overlayShadow: `${ROOT}/settings/shared_master/overlay_shadow.png`,
    settingRow: `${ROOT}/settings/shared_master/setting_row_base.png`,
    toggleTrack: `${ROOT}/settings/shared_master/toggle_track.png`,
    toggleHandle: `${ROOT}/settings/shared_master/toggle_handle.png`,
    replay: `${ROOT}/settings/shared_master/replay_entry_affordance.png`,
    support: `${ROOT}/settings/shared_master/support_entry_affordance.png`,
    logout: `${ROOT}/settings/shared_master/logout_entry_affordance.png`,
    close: `${ROOT}/settings/shared_master/close_affordance.png`,
    focusScrim: `${ROOT}/settings/shared_master/optional_focus_scrim.png`,
    confirmPanel: `${ROOT}/settings/shared_master/confirm_panel.png`,
    processingIndicator: `${ROOT}/settings/shared_master/processing_indicator.png`,
    failureIndicator: `${ROOT}/settings/shared_master/failure_indicator.png`,
    rootOff: `${ROOT}/settings/formal_authority/settings_root/settings_root_reduced_motion_off.png`,
    rootOn: `${ROOT}/settings/formal_authority/settings_root/settings_root_reduced_motion_on.png`,
    replayEntry: `${ROOT}/settings/formal_authority/replay/replay_entry.png`,
    supportEntry: `${ROOT}/settings/formal_authority/support/support_entry.png`,
    logoutEntry: `${ROOT}/settings/formal_authority/logout/logout_entry.png`,
    logoutConfirmation: `${ROOT}/settings/formal_authority/logout/logout_confirmation.png`,
    logoutProcessing: `${ROOT}/settings/formal_authority/logout/logout_processing.png`,
    logoutFailure: `${ROOT}/settings/formal_authority/logout/logout_failure.png`,
    logoutRetry: `${ROOT}/settings/formal_authority/logout/logout_retry.png`,
    logoutCancel: `${ROOT}/settings/formal_authority/logout/logout_cancel.png`,
    formalClose: `${ROOT}/settings/formal_authority/navigation/close.png`,
    formalBack: `${ROOT}/settings/formal_authority/navigation/back.png`,
  },
  restaurant: {
    noticeBase: `${ROOT}/restaurant/formal_authority/visual_family/construction_notice/construction_notice_base.png`,
    noticeBorder: `${ROOT}/restaurant/formal_authority/visual_family/construction_notice/construction_notice_border.png`,
    noticeShadow: `${ROOT}/restaurant/formal_authority/visual_family/construction_notice/construction_notice_shadow.png`,
    preview: `${ROOT}/restaurant/formal_authority/visual_family/preview/preview_safe_accent.png`,
    close: `${ROOT}/restaurant/formal_authority/visual_family/navigation/close_affordance.png`,
    back: `${ROOT}/restaurant/formal_authority/visual_family/navigation/back_affordance.png`,
  },
  growth: {
    treeRingBase: `${ROOT}/resources/growth/tree_ring/growth_tree_ring_base.png`,
    treeRingProgress: `${ROOT}/resources/growth/tree_ring/growth_tree_ring_progress.png`,
    treeRingReceiving: `${ROOT}/resources/growth/tree_ring/growth_tree_ring_receiving.png`,
    treeRingReducedMotion: `${ROOT}/resources/growth/tree_ring/growth_tree_ring_reduced_motion.png`,
    focus: `${ROOT}/resources/growth/effects/growth_focus_effect.png`,
    receiving: `${ROOT}/resources/growth/effects/growth_receiving_glow.png`,
    empty: `${ROOT}/resources/growth/effects/growth_empty_state.png`,
    recentPaper: `${ROOT}/resources/growth/recent_action/growth_recent_action_paper.png`,
    recentEmpty: `${ROOT}/resources/growth/recent_action/growth_recent_action_empty.png`,
    close: `${ROOT}/resources/growth/world_controls/growth_close_world_control.png`,
  },
  characters: {
    rabbitForest: "/runtime-assets/v006/seated/masters/char_rabbit_act_sit_right_3q_v006_master.png",
    marmotForest: "/runtime-assets/v006/seated/masters/char_marmot_act_sit_left_3q_v006_master.png",
    rabbitTreehouse: "/runtime-assets/v006/seated/masters/char_rabbit_act_sit_right_3q_v006_master.png",
    marmotTreehouse: "/runtime-assets/v006/seated/masters/char_marmot_act_sit_left_3q_v006_master.png",
  },
} as const;

export const FORMAL_RUNTIME_ROUTE_COUNTS = {
  globalHudFamilies: 1,
  bottomNavigation: 0,
  proxyCharacters: 0,
  legacyRewardCards: 0,
  settlementCards: 0,
  merchantMissionP0: 0,
  missionClaimP0: 1,
  p1Executable: 0,
  flattenedReferencePartitions: 0,
} as const;
